import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Nav } from './Nav'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full h-full flex flex-col items-start justify-between p-24">
          <Nav />
          {children}
        </main>
      </body>
    </html>
  )
}
