# docker-compose file version
version: '3'

# app services
services:
  # database service
  db:
    # custom image with setup database
    image: postgres:14-alpine
    # container name
    env_file:
      - ./.env
    container_name: database
    # restart app always except when manually stoppped
    restart: unless-stopped
    # allow connection with native password
    ports:
      - 5432:5432
    # environment variables
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}

    volumes:
      - "./db:/var/lib/postgresql/data"

  frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile

      # Set envrionment variables based on the .env file
      env_file:
        - ./.env
      volumes:
        - ./frontend/src:/app/src
        - ./frontend/public:/app/public
      restart: always
      ports:
        - 3000:3000

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: backend
      ports:
        - '8000:8000'
      env_file:
        - ./.env
      depends_on:
        - db
      volumes:
        - ./backend/src:/app/src